version: '3.8'

services:
  # Command server (submission) - starts first and stays running
  submission:
    build:
      context: ./submissions/${SUBMISSION_FOLDER:-submission_a}
      dockerfile: Dockerfile
    container_name: submission_server
    volumes:
      - shared_pipes:/shared
    # Keep the container running and restart if it fails
    restart: unless-stopped
    # Add some debug output
    environment:
      - PYTHONUNBUFFERED=1
    # Health check to ensure the server is ready
    healthcheck:
      test: ["CMD", "test", "-p", "/shared/command_pipe", "-a", "-p", "/shared/response_pipe"]
      interval: 2s
      timeout: 1s
      retries: 30
      start_period: 5s
    networks:
      - isolated_network

  # Agent controller - runs the test commands and then exits
  agent:
    build:
      context: ./agent
      dockerfile: Dockerfile
    container_name: agent_controller
    volumes:
      - shared_pipes:/shared
    depends_on:
      submission:
        condition: service_healthy
    # Agent should exit after completing its work
    restart: "no"
    environment:
      - PYTHONUNBUFFERED=1
    # Agent has access to both networks for communication
    networks:
      - default
      - isolated_network

volumes:
  # Shared volume for named pipes communication
  shared_pipes:
    driver: local

networks:
  # Internal network with no external internet access
  isolated_network:
    driver: bridge
    internal: true
